# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('pid', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('warning', 'Warning'), ('info', 'Info'), ('debug', 'Debug')], max_length=255)),
                ('heartbeat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.HeartBeat')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.System')),
            ],
        ),
        migrations.AddField(
            model_name='workerlog',
            name='worker_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WorkerType'),
        ),
        migrations.AddField(
            model_name='workerinstance',
            name='worker_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WorkerType'),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.System'),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='worker_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WorkerInstance'),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='worker_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WorkerType'),
        ),
    ]
