# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workerinstance_heartbeat_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heartbeat',
            options={'get_latest_by': 'timestamp'},
        ),
        migrations.RemoveField(
            model_name='workerinstance',
            name='heartbeat_interval',
        ),
        migrations.AddField(
            model_name='workertype',
            name='heartbeat_interval',
            field=models.IntegerField(default=10),
        ),
    ]
