# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161116_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='workertype',
            name='maximum_capacity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='workertype',
            name='minimum_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
