# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161116_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='workertype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
