# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_workertype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='workertype',
            name='worker_friendly_name',
            field=models.TextField(null=True),
        ),
    ]
