# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workertype_worker_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workertype',
            name='worker_friendly_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
