# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161120_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeat',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
