# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_workertype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workertype',
            name='status',
            field=models.CharField(choices=[('STATUS_OFFLINE', 'Offline'), ('STATUS_ONLINE', 'Online'), ('STATUS_UNKNOWN', 'Unknown')], default='STATUS_UNKNOWN', max_length=255),
        ),
    ]
