# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_workertype_alive_beat_span'),
    ]

    operations = [
        migrations.AddField(
            model_name='workertype',
            name='allowable_interval_variance',
            field=models.FloatField(default=0.1),
        ),
    ]
