# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slackwebhook',
            name='limit_worker_types',
            field=models.ManyToManyField(blank=True, to='core.WorkerType'),
        ),
    ]
