# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack', '0002_auto_20161202_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='slackwebhook',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
