# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('junebug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='junebuginstance',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='junebuginstance',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
