# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('worker_name', models.CharField(max_length=255)),
                ('pid', models.IntegerField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.System')),
            ],
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.System'),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Worker'),
        ),
    ]
