# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='pid',
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='hostname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='pid',
            field=models.IntegerField(null=True),
        ),
    ]
