# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161105_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('pid', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Worker',
            new_name='WorkerType',
        ),
        migrations.RenameField(
            model_name='heartbeat',
            old_name='worker',
            new_name='worker_type',
        ),
        migrations.RemoveField(
            model_name='heartbeat',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='heartbeat',
            name='pid',
        ),
        migrations.AddField(
            model_name='workerinstance',
            name='worker_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.WorkerType'),
        ),
        migrations.AddField(
            model_name='heartbeat',
            name='worker_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.WorkerInstance'),
        ),
    ]
